# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  # Maintain dependencies for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
  # Maintain dependencies for Gradle
  # Maintain dependencies for submodules
  - package-ecosystem: "gitsubmodule"
    directory: "/"
    groups:
      docker:
        # Define patterns to include dependencies in the group (based on
        # dependency name)
        patterns:
          - "*"       # A wildcard that matches all dependencies in the package
          # ecosystem. Note: using "*" may open a large pull request
    schedule:
      interval: "daily" # Change this to weekly some time in the future when things settle down

  # Maintain dependencies for Docker
  - package-ecosystem: "docker"
    directory: "/"
    groups:
      docker:
        # Define patterns to include dependencies in the group (based on
        # dependency name)
        patterns:
          - "*"       # A wildcard that matches all dependencies in the package
          # ecosystem. Note: using "*" may open a large pull request
    schedule:
      interval: "weekly"